
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Anshuman@108

development:
  <<: *default
  database: samyati_backend_development

 
test:
  <<: *default
  database: samyati_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>